navikt/fp-uttak

- pom.xml
- src/main/java/no/nav/foreldrepenger/regler/uttak/felles/grunnlag/Periode.java
> Revert "Skriver bort lite brukt dependency (#80)"

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeRegel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FedrekvoteDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FellesperiodeDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ForeldrepengerDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifiserer.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/MødrekvoteDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmPeriodenStarterFørFamiliehendelse.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmPeriodenStarterFørLovligUttakFørFamiliehendelse.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmPeriodenStarterFørLovligUttakFørFødselTermin.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmSøknadGjelderTerminEllerFødsel.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/AdopsjonOrkestreringTest.java
Legger til sjekk av om søknaden gjelder adopsjon. Når adopsjon kan uttak ikke være forut for omsorgsovertakelse (her familiehendelse).
> Sjekk om perioden starter før familiehendelse ved søknad som gjelder adopsjon (TFP-3503)

- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/BeregnKontoer.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/Konfigurasjonsfaktorer.java
Følte for å redusere branchingen ....
> NOJIRA forenkle og skille 100/80

- pom.xml
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeGrunnlag.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeGrunnlagImpl.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeRegel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifiserer.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmPeriodenErEtterMaksgrenseForUttak.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmPeriodenErEtterNyStønadsperiode.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/Datoer.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/utfall/IkkeOppfyltÅrsak.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/OrkestreringTest.java
Måtte inn i knekk-lista. Gliphy generell flyt er oppdatert
Men denne påvirker maxdato. Hvordan er maxdato-sjekkene strukturert ?
> TFP-4687 regel for ny stønadsperiode

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmMinsterettUtenAktivitetskravHarDisponibleDager.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/utfall/TomKontoIdentifiserer.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningTest.java
Må kunne returnere minus dager slik at saldovisningen i GUI viser minus dager med warning i stedet for en gyldig 0
> TFP-4888 restdager minsterett og uten aktkrav kan gå i minus

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeRegel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/SjekkOmEnPartsPeriodeErFlerbarnsdager.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/RevurderingTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/TapendeSakOrkestreringTest.java
Ved tapende eller berørt: Dersom aktuell periode eller annen parts overlappende periode er flerbarnsdager, gå tilbake til normal flyt
> TFP-4935 samtidig uttak ved flerbarnsdager

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningTest.java
Enkelt tillegg tilsvarende utenAktivitetskrav
Koden og testene for BFHR/minsterett var allerede på plass merkelig nok
> TFP-4960 saldoutregning metode for å sjekke evt minsterett

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/MinsterettOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/SaldoUtregningTjenesteTest.java
Ikke frigi flerbarnsdager. OBS på tilfelle der begge har flerbarnsdager - mulig den også skal endres til å ikke frigi.
En del tester rundt saldoutregning for flerbarn og minsterett for å forstå oppførsel
> NOJIRA Berørt/tapende skal ikke stjele flerbarnsdager

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeRegel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/SaldoUtregningTjenesteTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/TapendeSakOrkestreringTest.java
> TFP-4935 samtidige flerbarnsdager - minst en må velge samtidig

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FarUttakRundtFødsel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/konfig/Konfigurasjon.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/konfig/ParameterVerdier.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/konfig/StandardKonfigurasjon.java
For å kunne bruke fra Saldotjeneste + legge opp failsafe oppslag i konfigurasjon når vi flytter datogrensen
> TFP-4961 rette noen behov oppdaget ved integrasjon i fpsak

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeRegel.java
dette tar ned byggetiden fra 160s til 21s
> NOJIRA bedre ytelse i regeloppsett

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePerioderRegelOrkestrering.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningGrunnlag.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/utfall/TomKontoIdentifiserer.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/OrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/TapendeSakOrkestreringTest.java
Redusere knekking av ikke-kvote-tilfelle
> TFP-5032 det er kun fk som kan tømme de 10 dagene rundt fødsel

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifiserer.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ForeldrepengerDelregelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/OrkestreringTest.java
Må sikre at mor knekkes etter 6 uker pga forbud mot gradering
> TFP-5032 mor kan ikke gradere første 6 uker

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ManglendeSøktPeriodeDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmErAlleDisponibleDagerIgjenMinsterett.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ManglendeSøktOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/OrkestreringTest.java
https://confluence.adeo.no/x/c3YBGQ
nytt sluttpunk 1089
> 4102 avslagsårsak for bfhr og det bare er igjen dager med minsterett

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/Trekkdager.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/ForbruksTeller.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningFlerbarnsdager.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningUtil.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/Stønadskonto.java
Er dette en retning å gå i ?
Kunne kanskje skåret ut en del tapende-logikk til en egen klasse ?
> SaldoUtregning - utskilling av forbrukstelling for søker

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/ForbruksTeller.java
Denne vil bare ta min over tilfelle der det er aktivitet fra start (dvs første periode som telles)
> NOJIRA Hindre rekursjon dersom flere tilkommete aktiviteter

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ForeldrepengerDelregel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmMinsterettBalansertUttak.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmTilgjengeligeDagerPåNoenAktiviteteneForSøktStønadskonto.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningFlerbarnsdager.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/utfall/InnvilgetÅrsak.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/AvslagAktivitetskravOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ForeldrepengerDelregelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/MinsterettOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningFlerbarnsdagerTest.java
oppdatert https://confluence.adeo.no/x/5YL_Fw
> TFP-5104 flerbarnsdager trekker fra minsteretten

- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/Minsterett.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/StønadskontoRegelOrkestrering.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePerioderRegelOrkestrering.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/felles/grunnlag/Periode.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/konfig/Konfigurasjon.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/konfig/KonfigurasjonBuilder.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/konfig/StandardKonfigurasjon.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/MinsterettTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/PrematurukerUtilTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/DelRegelTestUtil.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifisererTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ManglendeSøktePerioderForSammenhengendeUttakTjenesteTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ManglendeSøktePerioderTjenesteTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/RegelResultatBehandlerTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmTidsperiodeForbeholdtMorTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/konfig/StandardKonfigurasjonTest.java
Starten på å samle/konsolidere konfig. Ser det OK ut?
> NOJIRA Samle konfigurasjon for sak og søknad

- src/main/java/no/nav/foreldrepenger/regler/SøknadsfristUtil.java
Utvider SF-util med metode tilsvarende vilkåret. 
Sanerer regelen i neste omgang
> TFP-5065 enkel util som tilsvarer sf-vilkåret

- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/BeregnKontoer.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/betingelser/SjekkOmAnnenForelderHarTilsvarendeRettEØS.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/betingelser/SjekkOmAnnenForelderHarTilsvarendeRettForEØS.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/grunnlag/BeregnKontoerGrunnlag.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/beregnkontoer/StønadskontoRegelOrkestreringTest.java
La inn egen diamant (Gliffy oppdatert).
Gjenstår avklaring om far/rett mor/eøs og Foreldrepenger Før Fødsel. Regel SjekkOmFødsel blir berørt
> TFP-5159 en part ikke rett i Norge men har opptjening fra EØS

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifiserer.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseOrkestreringTest.java
Tatt med test som ga problem. Kunne alternativt lagt til sjekker på harSøktOmOverføringAvKvote (+utsettelse?) i SjekkOmPeriodenInnenforUkerReservertMor
> NOJIRA knekk ved fødsel/termin + 6u for tilfelle med kvoter og lang overføring

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePerioderRegelOrkestrering.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifiserer.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/Arbeid.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/Arbeidsforhold.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/EndringAvStilling.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ArbeidsforholdTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/OrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/RegelResultatBehandlerTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseSammenhengendeUttakOrkestreringTest.java
Kanskje ikke lekreste metoden, men kan stå slik til vi tar i bruk timeline (eller pensjonerer sammenhengende uttak)
> NOJIRA Ta med arbeid fra IAY-register pga utsettelse av tilkommet arbeid u/ber.andel

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeGrunnlag.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeGrunnlagImpl.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmOmsorgHelePerioden.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/RettOgOmsorg.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/AdopsjonOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FedrekvoteDelregelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FedrekvoteOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FellesperiodeDelregelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ForeldrepengerDelregelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/MødrekvoteDelregelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/MødrekvoteOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/OrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/StebarnsadopsjonDelRegelTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/TapendeSakOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseOrkestreringTest.java
Innført harOmsorg som Boolean og testet slik det var før + fjernet dokumentasjon i alle tester.
Bare en test i MK hadde en kortere periode uten omsorg - ikke relevant lenger
> TFP-5036 expand regler for Boolean harOmsorg

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeRegel.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/GraderingOrkestreringTest.java
Gliphy / generelle er oppdaert
> TFP-5414 fritt uttak kan ha gradering tilbake i tid

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmErAleneomsorg.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/regelflyt/ForeldrepengerDelregel.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/ForeldrepengerDelregelTest.java
oppdatert https://confluence.adeo.no/pages/viewpage.action?pageId=402555621
> TFP-5453 mødre med aleneomsorg skal få riktig oppfyltårsak

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/aktkrav/SjekkOmSkalTrekkeDagerFraKonto.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/regelflyt/AvslagAktivitetskravDelregel.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/AvslagAktivitetskravOrkestreringTest.java
Gliffy oppdatert. Blir ikke dette omtrent riktig. Bør vi ta med sjekk på FELLESPERIODE i tillegg?
> TFP-5634 trekk dager ved avslag for sammenhengende+bfhr

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifiserer.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/GraderingOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/KnekkpunktIdentifisererTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseSammenhengendeUttakOrkestreringTest.java
trenger ikke knekk ettersom disse nå innvilges
> TFP-5658 knekker ikke på mottatt dato for gradering og utsettelse arbeid

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/regelflyt/UtsettelseDelregel.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseOrkestreringTest.java
skal sjekke med marte hva som gjelder første 6 ukene
> FAGSYSTEM-329508 innvilger fri utsettelse for aleneomsorg etter uke 6

- pom.xml
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeResultat.java
For å slippe å konstruere repo:versjon i fpsak
> Nare 263 og bruk regelversjon=prosjekt:versjon

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/regelflyt/UtsettelseDelregel.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/UtsettelseOrkestreringTest.java
Innvilger far utsettelse første 6 ukene. Kommer inn utsettelser pga pleiepengevedtak
Tar vare på sjekken om far har rett til dager rundt fødsel -> går fortsatt til manuell behandling
Oppdatert flyten på [confluence ](https://confluence.adeo.no/pages/viewpage.action?pageId=417532466)
> FAGSYSTEM-368858 innvilger fedre utsettelser første 6 ukene

- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeGrunnlag.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePeriodeGrunnlagImpl.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/FastsettePerioderRegelOrkestrering.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/Trekkdager.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/betingelser/SjekkOmOverlapperMedAnnenPartEøs.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/AnnenPart.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/AnnenpartUttakPeriode.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/grunnlag/AnnenpartUttakPeriodeAktivitet.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/regelflyt/FastsettePeriodeRegel.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregning.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningGrunnlag.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningTjeneste.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/utfall/IkkeOppfyltÅrsak.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/util/ManglendeSøktePerioderTjeneste.java
- src/main/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/util/SamtidigUttakUtil.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/EøsOrkestreringTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/SaldoUtregningTjenesteTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/saldo/SaldoUtregningTest.java
- src/test/java/no/nav/foreldrepenger/regler/uttak/fastsetteperiode/util/ManglendeSøktePerioderTjenesteTest.java
tapende betyr at saldotutregning trekker for alle annenparts perioder først
> TFP-6302: Eøs perioder
